// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: game.proto

#include "game.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_game_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_game_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_obj_user_game_record;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_game_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_obj_user_info;
}  // namespace protobuf_game_2eproto
namespace pt {
class reg_loginDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<reg_login>
      _instance;
} _reg_login_default_instance_;
class obj_user_infoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<obj_user_info>
      _instance;
} _obj_user_info_default_instance_;
class obj_user_game_recordDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<obj_user_game_record>
      _instance;
} _obj_user_game_record_default_instance_;
class rsp_loginDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<rsp_login>
      _instance;
} _rsp_login_default_instance_;
}  // namespace pt
namespace protobuf_game_2eproto {
static void InitDefaultsreg_login() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pt::_reg_login_default_instance_;
    new (ptr) ::pt::reg_login();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pt::reg_login::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_reg_login =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsreg_login}, {}};

static void InitDefaultsobj_user_info() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pt::_obj_user_info_default_instance_;
    new (ptr) ::pt::obj_user_info();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pt::obj_user_info::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_obj_user_info =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsobj_user_info}, {}};

static void InitDefaultsobj_user_game_record() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pt::_obj_user_game_record_default_instance_;
    new (ptr) ::pt::obj_user_game_record();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pt::obj_user_game_record::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_obj_user_game_record =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsobj_user_game_record}, {}};

static void InitDefaultsrsp_login() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::pt::_rsp_login_default_instance_;
    new (ptr) ::pt::rsp_login();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::pt::rsp_login::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_rsp_login =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsrsp_login}, {
      &protobuf_game_2eproto::scc_info_obj_user_info.base,
      &protobuf_game_2eproto::scc_info_obj_user_game_record.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_reg_login.base);
  ::google::protobuf::internal::InitSCC(&scc_info_obj_user_info.base);
  ::google::protobuf::internal::InitSCC(&scc_info_obj_user_game_record.base);
  ::google::protobuf::internal::InitSCC(&scc_info_rsp_login.base);
}

}  // namespace protobuf_game_2eproto
namespace pt {
bool rsp_login_RET_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 10:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const rsp_login_RET rsp_login::SUCCESS;
const rsp_login_RET rsp_login::ACCOUNT_NULL;
const rsp_login_RET rsp_login::ACCOUNT_LOCK;
const rsp_login_RET rsp_login::PASSWORD_ERROR;
const rsp_login_RET rsp_login::ERROR;
const rsp_login_RET rsp_login::RET_MIN;
const rsp_login_RET rsp_login::RET_MAX;
const int rsp_login::RET_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void reg_login::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int reg_login::kUsernameFieldNumber;
const int reg_login::kPasswordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

reg_login::reg_login()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2eproto::scc_info_reg_login.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.reg_login)
}
reg_login::reg_login(const reg_login& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.username().size() > 0) {
    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.password().size() > 0) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  // @@protoc_insertion_point(copy_constructor:pt.reg_login)
}

void reg_login::SharedCtor() {
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

reg_login::~reg_login() {
  // @@protoc_insertion_point(destructor:pt.reg_login)
  SharedDtor();
}

void reg_login::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void reg_login::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const reg_login& reg_login::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2eproto::scc_info_reg_login.base);
  return *internal_default_instance();
}


void reg_login::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.reg_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool reg_login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:pt.reg_login)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string username = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), static_cast<int>(this->username().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.reg_login.username"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string password = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.reg_login.password"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.reg_login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.reg_login)
  return false;
#undef DO_
}

void reg_login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.reg_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string username = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), static_cast<int>(this->username().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.reg_login.username");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  // string password = 2;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.reg_login.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->password(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:pt.reg_login)
}

size_t reg_login::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.reg_login)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string username = 1;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // string password = 2;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void reg_login::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const reg_login*>(&from));
}

void reg_login::MergeFrom(const reg_login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.reg_login)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
}

void reg_login::CopyFrom(const reg_login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.reg_login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool reg_login::IsInitialized() const {
  return true;
}

void reg_login::Swap(reg_login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void reg_login::InternalSwap(reg_login* other) {
  using std::swap;
  username_.Swap(&other->username_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  password_.Swap(&other->password_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string reg_login::GetTypeName() const {
  return "pt.reg_login";
}


// ===================================================================

void obj_user_info::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int obj_user_info::kNicknameFieldNumber;
const int obj_user_info::kIconFieldNumber;
const int obj_user_info::kCoinFieldNumber;
const int obj_user_info::kLocationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

obj_user_info::obj_user_info()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2eproto::scc_info_obj_user_info.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.obj_user_info)
}
obj_user_info::obj_user_info(const obj_user_info& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  nickname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.nickname().size() > 0) {
    nickname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nickname_);
  }
  icon_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.icon().size() > 0) {
    icon_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.icon_);
  }
  location_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.location().size() > 0) {
    location_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.location_);
  }
  coin_ = from.coin_;
  // @@protoc_insertion_point(copy_constructor:pt.obj_user_info)
}

void obj_user_info::SharedCtor() {
  nickname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  icon_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  location_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  coin_ = GOOGLE_LONGLONG(0);
}

obj_user_info::~obj_user_info() {
  // @@protoc_insertion_point(destructor:pt.obj_user_info)
  SharedDtor();
}

void obj_user_info::SharedDtor() {
  nickname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  icon_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  location_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void obj_user_info::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const obj_user_info& obj_user_info::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2eproto::scc_info_obj_user_info.base);
  return *internal_default_instance();
}


void obj_user_info::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.obj_user_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  nickname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  icon_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  location_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  coin_ = GOOGLE_LONGLONG(0);
  _internal_metadata_.Clear();
}

bool obj_user_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:pt.obj_user_info)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string nickname = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_nickname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->nickname().data(), static_cast<int>(this->nickname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.obj_user_info.nickname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string icon = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_icon()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->icon().data(), static_cast<int>(this->icon().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.obj_user_info.icon"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 coin = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &coin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string location = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_location()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->location().data(), static_cast<int>(this->location().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.obj_user_info.location"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.obj_user_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.obj_user_info)
  return false;
#undef DO_
}

void obj_user_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.obj_user_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string nickname = 1;
  if (this->nickname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->nickname().data(), static_cast<int>(this->nickname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.obj_user_info.nickname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->nickname(), output);
  }

  // string icon = 2;
  if (this->icon().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->icon().data(), static_cast<int>(this->icon().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.obj_user_info.icon");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->icon(), output);
  }

  // int64 coin = 3;
  if (this->coin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->coin(), output);
  }

  // string location = 4;
  if (this->location().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->location().data(), static_cast<int>(this->location().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.obj_user_info.location");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->location(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:pt.obj_user_info)
}

size_t obj_user_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.obj_user_info)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string nickname = 1;
  if (this->nickname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->nickname());
  }

  // string icon = 2;
  if (this->icon().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->icon());
  }

  // string location = 4;
  if (this->location().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->location());
  }

  // int64 coin = 3;
  if (this->coin() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->coin());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void obj_user_info::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const obj_user_info*>(&from));
}

void obj_user_info::MergeFrom(const obj_user_info& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.obj_user_info)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.nickname().size() > 0) {

    nickname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.nickname_);
  }
  if (from.icon().size() > 0) {

    icon_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.icon_);
  }
  if (from.location().size() > 0) {

    location_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.location_);
  }
  if (from.coin() != 0) {
    set_coin(from.coin());
  }
}

void obj_user_info::CopyFrom(const obj_user_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.obj_user_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool obj_user_info::IsInitialized() const {
  return true;
}

void obj_user_info::Swap(obj_user_info* other) {
  if (other == this) return;
  InternalSwap(other);
}
void obj_user_info::InternalSwap(obj_user_info* other) {
  using std::swap;
  nickname_.Swap(&other->nickname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  icon_.Swap(&other->icon_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  location_.Swap(&other->location_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(coin_, other->coin_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string obj_user_info::GetTypeName() const {
  return "pt.obj_user_info";
}


// ===================================================================

void obj_user_game_record::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int obj_user_game_record::kTimeFieldNumber;
const int obj_user_game_record::kKillFieldNumber;
const int obj_user_game_record::kDeadFieldNumber;
const int obj_user_game_record::kAssistFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

obj_user_game_record::obj_user_game_record()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2eproto::scc_info_obj_user_game_record.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.obj_user_game_record)
}
obj_user_game_record::obj_user_game_record(const obj_user_game_record& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.time().size() > 0) {
    time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
  }
  ::memcpy(&kill_, &from.kill_,
    static_cast<size_t>(reinterpret_cast<char*>(&assist_) -
    reinterpret_cast<char*>(&kill_)) + sizeof(assist_));
  // @@protoc_insertion_point(copy_constructor:pt.obj_user_game_record)
}

void obj_user_game_record::SharedCtor() {
  time_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&kill_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&assist_) -
      reinterpret_cast<char*>(&kill_)) + sizeof(assist_));
}

obj_user_game_record::~obj_user_game_record() {
  // @@protoc_insertion_point(destructor:pt.obj_user_game_record)
  SharedDtor();
}

void obj_user_game_record::SharedDtor() {
  time_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void obj_user_game_record::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const obj_user_game_record& obj_user_game_record::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2eproto::scc_info_obj_user_game_record.base);
  return *internal_default_instance();
}


void obj_user_game_record::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.obj_user_game_record)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  time_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&kill_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&assist_) -
      reinterpret_cast<char*>(&kill_)) + sizeof(assist_));
  _internal_metadata_.Clear();
}

bool obj_user_game_record::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:pt.obj_user_game_record)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string time = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_time()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->time().data(), static_cast<int>(this->time().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "pt.obj_user_game_record.time"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 kill = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &kill_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 dead = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &dead_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 assist = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &assist_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.obj_user_game_record)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.obj_user_game_record)
  return false;
#undef DO_
}

void obj_user_game_record::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.obj_user_game_record)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string time = 1;
  if (this->time().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->time().data(), static_cast<int>(this->time().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "pt.obj_user_game_record.time");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->time(), output);
  }

  // int32 kill = 2;
  if (this->kill() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->kill(), output);
  }

  // int32 dead = 3;
  if (this->dead() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->dead(), output);
  }

  // int32 assist = 4;
  if (this->assist() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->assist(), output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:pt.obj_user_game_record)
}

size_t obj_user_game_record::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.obj_user_game_record)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // string time = 1;
  if (this->time().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->time());
  }

  // int32 kill = 2;
  if (this->kill() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->kill());
  }

  // int32 dead = 3;
  if (this->dead() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->dead());
  }

  // int32 assist = 4;
  if (this->assist() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->assist());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void obj_user_game_record::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const obj_user_game_record*>(&from));
}

void obj_user_game_record::MergeFrom(const obj_user_game_record& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.obj_user_game_record)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.time().size() > 0) {

    time_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.time_);
  }
  if (from.kill() != 0) {
    set_kill(from.kill());
  }
  if (from.dead() != 0) {
    set_dead(from.dead());
  }
  if (from.assist() != 0) {
    set_assist(from.assist());
  }
}

void obj_user_game_record::CopyFrom(const obj_user_game_record& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.obj_user_game_record)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool obj_user_game_record::IsInitialized() const {
  return true;
}

void obj_user_game_record::Swap(obj_user_game_record* other) {
  if (other == this) return;
  InternalSwap(other);
}
void obj_user_game_record::InternalSwap(obj_user_game_record* other) {
  using std::swap;
  time_.Swap(&other->time_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(kill_, other->kill_);
  swap(dead_, other->dead_);
  swap(assist_, other->assist_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string obj_user_game_record::GetTypeName() const {
  return "pt.obj_user_game_record";
}


// ===================================================================

void rsp_login::InitAsDefaultInstance() {
  ::pt::_rsp_login_default_instance_._instance.get_mutable()->user_info_ = const_cast< ::pt::obj_user_info*>(
      ::pt::obj_user_info::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int rsp_login::kRetFieldNumber;
const int rsp_login::kUserInfoFieldNumber;
const int rsp_login::kRecordFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

rsp_login::rsp_login()
  : ::google::protobuf::MessageLite(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_game_2eproto::scc_info_rsp_login.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:pt.rsp_login)
}
rsp_login::rsp_login(const rsp_login& from)
  : ::google::protobuf::MessageLite(),
      _internal_metadata_(NULL),
      record_(from.record_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_user_info()) {
    user_info_ = new ::pt::obj_user_info(*from.user_info_);
  } else {
    user_info_ = NULL;
  }
  ret_ = from.ret_;
  // @@protoc_insertion_point(copy_constructor:pt.rsp_login)
}

void rsp_login::SharedCtor() {
  ::memset(&user_info_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ret_) -
      reinterpret_cast<char*>(&user_info_)) + sizeof(ret_));
}

rsp_login::~rsp_login() {
  // @@protoc_insertion_point(destructor:pt.rsp_login)
  SharedDtor();
}

void rsp_login::SharedDtor() {
  if (this != internal_default_instance()) delete user_info_;
}

void rsp_login::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const rsp_login& rsp_login::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_game_2eproto::scc_info_rsp_login.base);
  return *internal_default_instance();
}


void rsp_login::Clear() {
// @@protoc_insertion_point(message_clear_start:pt.rsp_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  record_.Clear();
  if (GetArenaNoVirtual() == NULL && user_info_ != NULL) {
    delete user_info_;
  }
  user_info_ = NULL;
  ret_ = 0;
  _internal_metadata_.Clear();
}

bool rsp_login::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::LiteUnknownFieldSetter unknown_fields_setter(
      &_internal_metadata_);
  ::google::protobuf::io::StringOutputStream unknown_fields_output(
      unknown_fields_setter.buffer());
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_output, false);
  // @@protoc_insertion_point(parse_start:pt.rsp_login)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 ret = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ret_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .pt.obj_user_info user_info = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_user_info()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .pt.obj_user_game_record record = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_record()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:pt.rsp_login)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:pt.rsp_login)
  return false;
#undef DO_
}

void rsp_login::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:pt.rsp_login)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 ret = 1;
  if (this->ret() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->ret(), output);
  }

  // .pt.obj_user_info user_info = 2;
  if (this->has_user_info()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, this->_internal_user_info(), output);
  }

  // repeated .pt.obj_user_game_record record = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->record_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      3,
      this->record(static_cast<int>(i)),
      output);
  }

  output->WriteRaw((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).data(),
                   static_cast<int>((::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size()));
  // @@protoc_insertion_point(serialize_end:pt.rsp_login)
}

size_t rsp_login::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pt.rsp_login)
  size_t total_size = 0;

  total_size += (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()).size();

  // repeated .pt.obj_user_game_record record = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->record_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->record(static_cast<int>(i)));
    }
  }

  // .pt.obj_user_info user_info = 2;
  if (this->has_user_info()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *user_info_);
  }

  // int32 ret = 1;
  if (this->ret() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ret());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void rsp_login::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const rsp_login*>(&from));
}

void rsp_login::MergeFrom(const rsp_login& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:pt.rsp_login)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  record_.MergeFrom(from.record_);
  if (from.has_user_info()) {
    mutable_user_info()->::pt::obj_user_info::MergeFrom(from.user_info());
  }
  if (from.ret() != 0) {
    set_ret(from.ret());
  }
}

void rsp_login::CopyFrom(const rsp_login& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pt.rsp_login)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool rsp_login::IsInitialized() const {
  return true;
}

void rsp_login::Swap(rsp_login* other) {
  if (other == this) return;
  InternalSwap(other);
}
void rsp_login::InternalSwap(rsp_login* other) {
  using std::swap;
  CastToBase(&record_)->InternalSwap(CastToBase(&other->record_));
  swap(user_info_, other->user_info_);
  swap(ret_, other->ret_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::std::string rsp_login::GetTypeName() const {
  return "pt.rsp_login";
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace pt
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::pt::reg_login* Arena::CreateMaybeMessage< ::pt::reg_login >(Arena* arena) {
  return Arena::CreateInternal< ::pt::reg_login >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::pt::obj_user_info* Arena::CreateMaybeMessage< ::pt::obj_user_info >(Arena* arena) {
  return Arena::CreateInternal< ::pt::obj_user_info >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::pt::obj_user_game_record* Arena::CreateMaybeMessage< ::pt::obj_user_game_record >(Arena* arena) {
  return Arena::CreateInternal< ::pt::obj_user_game_record >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::pt::rsp_login* Arena::CreateMaybeMessage< ::pt::rsp_login >(Arena* arena) {
  return Arena::CreateInternal< ::pt::rsp_login >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
