
#include <Shlobj.h>  
#include <stdio.h>  
#include <locale.h>  

int main()  
{  
	setlocale(LC_ALL, "chs");  

	TCHAR szPath[MAX_PATH];  

	int CSIDL[] = {  
		CSIDL_ADMINTOOLS,
		CSIDL_APPDATA,
		CSIDL_CDBURN_AREA,
		CSIDL_COMMON_ADMINTOOLS,
		CSIDL_COMMON_APPDATA,  
		CSIDL_COMMON_DESKTOPDIRECTORY,
		CSIDL_COMMON_DOCUMENTS,
		CSIDL_COMMON_FAVORITES,
		CSIDL_COMMON_MUSIC,
		CSIDL_COMMON_PICTURES,
		CSIDL_COMMON_PROGRAMS,
		CSIDL_COMMON_STARTMENU,
		CSIDL_COMMON_STARTUP,  
		CSIDL_COMMON_TEMPLATES,
		CSIDL_COMMON_VIDEO,
		CSIDL_COOKIES,
		CSIDL_FAVORITES,  
		CSIDL_HISTORY,
		CSIDL_INTERNET_CACHE,
		CSIDL_LOCAL_APPDATA,
		CSIDL_MYDOCUMENTS, 
		CSIDL_MYMUSIC, 
		CSIDL_MYPICTURES, 
		CSIDL_MYVIDEO, 
		CSIDL_PROFILE, 
		CSIDL_PROGRAM_FILES,  
		CSIDL_PROGRAM_FILES_COMMON, 
		CSIDL_PROGRAMS,  
		CSIDL_RECENT,    
		CSIDL_SENDTO,  
		CSIDL_STARTMENU,  
		CSIDL_STARTUP,  
		CSIDL_SYSTEM,  
		CSIDL_TEMPLATES,
		CSIDL_WINDOWS,  
		0  
	};  

	for (int i = 0; CSIDL[i]; i++) 
	{
		if (SUCCEEDED(SHGetFolderPath(NULL, CSIDL[i], NULL, SHGFP_TYPE_CURRENT, szPath)))  
			wprintf(L"%d, %s\n", i, szPath);
	}

	system("pause");
	return 0;  
}  